import type { Metadata } from "next";
import {  Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { getServerSession } from "next-auth";
import { Toaster } from "@/components/ui/toaster";

const nunito = Nunito_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={nunito.className}>
        <main vaul-drawer-wrapper="">
          <Providers session={session}>
            {
              <>
                <Navbar />
                <Toaster  />
                {children}
              </>
            }
          </Providers>
        </main>
      </body>
    </html>
  );
}
